package com.rahim.yadino.enums.message

enum class MessageUi(val type:Int) {
  ERROR_GET_PROCESS(0),
  ERROR_EQUAL_ROUTINE_MESSAGE(1),
  ERROR_SAVE_REMINDER(2),
  ERROR_NOTIFICATION_PERMISSION(3),
  ERROR_REMINDER_PERMISSION(4),
  ERROR_NOTIFICATION_AND_REMINDER_PERMISSION(5),
  ERROR_TIME_PASSED(6),
  ERROR_SEARCH_ROUTINE(7),
  SUCCESS_SAVE_REMINDER(8),
  SUCCESS_UPDATE_REMINDER(9),
  ERROR_UPDATE_REMINDER(10),
  ERROR_REMOVE_REMINDER(11),
  SUCCESS_ADD_NOTE(12),
  ERROR_ADD_NOTE(13),
}
