package com.rahim.yadino.enums.error

enum class ErrorMessageCode(val code:Int) {
    ERROR_GET_PROCESS(0),
    EQUAL_ROUTINE_MESSAGE(1),
    ERROR_SAVE_PROSES(2),
    ERROR_NOTIFICATION_PERMISSION(3),
    ERROR_REMINDER_PERMISSION(4),
    ERROR_NOTIFICATION_AND_REMINDER_PERMISSION(5),
    ERROR_TIME_PASSED(6),
}
